export const GUIDELINES_DB = [
  { title: { en: 'KDIGO 2024 CKD Guideline', id: 'Pedoman PGK KDIGO 2024' }, category: 'Nephrology', content: { en: 'Comprehensive guidelines for the evaluation and management of Chronic Kidney Disease, emphasizing eGFR and albuminuria.', id: 'Pedoman komprehensif untuk evaluasi dan manajemen Penyakit Ginjal Kronis, menekankan eGFR dan albuminuria.' }, pdfUrl: 'https://kdigo.org/wp-content/uploads/2024/03/KDIGO-2024-CKD-Guideline.pdf' },
  { title: { en: 'AHA/ACC 2023 Coronary Disease', id: 'AHA/ACC 2023 Penyakit Koroner' }, category: 'Cardiology', content: { en: 'Guideline for the management of patients with chronic coronary disease, focusing on lifestyle, medical therapy, and revascularization.', id: 'Pedoman untuk manajemen pasien dengan penyakit koroner kronis, dengan fokus pada gaya hidup, terapi medis, dan revaskularisasi.' } },
  { title: { en: 'IDSA/ATS 2019 CAP Guidelines', id: 'Pedoman CAP IDSA/ATS 2019' }, category: 'Pulmonology', content: { en: 'Diagnosis and treatment of adults with community-acquired pneumonia, including macrolide and beta-lactam recommendations.', id: 'Diagnosis dan pengobatan orang dewasa dengan pneumonia didapat dari komunitas, termasuk rekomendasi makrolida dan beta-laktam.' } },
  { title: { en: 'WGO 2023 Probiotics & Prebiotics', id: 'WGO 2023 Probiotik & Prebiotik' }, category: 'Gastroenterology', content: { en: 'Global guidelines detailing evidence-based indications for probiotic and prebiotic strains in gastrointestinal disorders.', id: 'Pedoman global yang merinci indikasi berbasis bukti untuk strain probiotik dan prebiotik pada gangguan gastrointestinal.' } },
  { title: { en: 'EASD/ADA 2022 Hyperglycemia', id: 'Hiperglikemia EASD/ADA 2022' }, category: 'Endocrinology', content: { en: 'Consensus report on the management of hyperglycemia in type 2 diabetes, highlighting weight management and cardiovascular risk.', id: 'Laporan konsensus tentang manajemen hiperglikemia pada diabetes tipe 2, menyoroti manajemen berat badan dan risiko kardiovaskular.' } },
  { title: { en: 'GINA 2023 Asthma Strategy', id: 'Strategi Asma GINA 2023' }, category: 'Pulmonology', content: { en: 'Global strategy for asthma management and prevention, advocating against SABA-only treatment.', id: 'Strategi global untuk manajemen dan pencegahan asma, merekomendasikan untuk menghindari pengobatan hanya dengan SABA.' } },
  { title: { en: 'GOLD 2024 COPD Strategy', id: 'Strategi PPOK GOLD 2024' }, category: 'Pulmonology', content: { en: 'Diagnosis, management, and prevention of COPD, introducing the ABE assessment tool and blood eosinophil guides.', id: 'Diagnosis, tata laksana, dan pencegahan PPOK, memperkenalkan alat penilaian ABE dan panduan eosinofil darah.' } },
  { title: { en: 'AACE 2023 T2D Algorithm', id: 'Algoritma DM Tipe 2 AACE 2023' }, category: 'Endocrinology', content: { en: 'Comprehensive algorithm for type 2 diabetes management, featuring complication-centric approaches.', id: 'Algoritma komprehensif untuk manajemen diabetes tipe 2, menampilkan pendekatan yang berpusat pada komplikasi.' } },
  { title: { en: 'ESC 2024 Hypertension', id: 'Hipertensi ESC 2024' }, category: 'Cardiology', content: { en: 'European guidelines for the management of elevated blood pressure and hypertension, updating target blood pressure goals.', id: 'Pedoman Eropa untuk manajemen tekanan darah tinggi dan hipertensi, memperbarui target pencapaian tekanan darah.' } },
  { title: { en: 'ACOG Gestational Hypertension', id: 'Hipertensi Gestasional ACOG' }, category: 'Obstetrics', content: { en: 'Practice bulletin on the diagnosis and management of gestational hypertension and preeclampsia.', id: 'Buletin praktik tentang diagnosis dan pengelolaan hipertensi gestasional dan preeklamsia.' } }
];
