export const ICD10_DB = [
  { code: 'J00', name: 'Acute nasopharyngitis [common cold]', indonesian: 'Nasofaringitis akut [selesma]' },
  { code: 'J01', name: 'Acute sinusitis', indonesian: 'Sinusitis akut' },
  { code: 'J02', name: 'Acute pharyngitis', indonesian: 'Faringitis akut' },
  { code: 'J03', name: 'Acute tonsillitis', indonesian: 'Tonsilitis akut' },
  { code: 'J06.9', name: 'Acute upper respiratory infection, unspecified', indonesian: 'Infeksi saluran pernapasan atas akut, tidak spesifik (ISPA)'},
  { code: 'J20', name: 'Acute bronchitis', indonesian: 'Bronkitis akut' },
  { code: 'J44.9', name: 'Chronic obstructive pulmonary disease, unspecified', indonesian: 'Penyakit paru obstruktif kronis (PPOK)' },
  { code: 'I10', name: 'Essential (primary) hypertension', indonesian: 'Hipertensi esensial (primer)' },
  { code: 'I15', name: 'Secondary hypertension', indonesian: 'Hipertensi sekunder' },
  { code: 'I20', name: 'Angina pectoris', indonesian: 'Angina pektoris' },
  { code: 'I21', name: 'Acute myocardial infarction', indonesian: 'Infark miokard akut' },
  { code: 'I63.9', name: 'Cerebral infarction, unspecified', indonesian: 'Infark serebral / Stroke iskemik' },
  { code: 'E10', name: 'Type 1 diabetes mellitus', indonesian: 'Diabetes melitus tipe 1' },
  { code: 'E11', name: 'Type 2 diabetes mellitus', indonesian: 'Diabetes melitus tipe 2' },
  { code: 'A09', name: 'Infectious gastroenteritis and colitis', indonesian: 'Gastroenteritis dan kolitis infeksius / Diare' },
  { code: 'A91', name: 'Dengue haemorrhagic fever', indonesian: 'Demam Berdarah Dengue (DBD)' },
  { code: 'B01', name: 'Varicella [chickenpox]', indonesian: 'Cacar air (Varisela)' },
  { code: 'K29.7', name: 'Gastritis, unspecified', indonesian: 'Gastritis, tidak spesifik' },
  { code: 'K35', name: 'Acute appendicitis', indonesian: 'Apendisitis akut' },
  { code: 'N39.0', name: 'Urinary tract infection, site not specified', indonesian: 'Infeksi saluran kemih (ISK)' },
  { code: 'R50.9', name: 'Fever, unspecified', indonesian: 'Demam, tidak spesifik' },
  { code: 'R51', name: 'Headache', indonesian: 'Sakit kepala / Nyeri kepala' },
  { code: 'Z00.0', name: 'General medical examination', indonesian: 'Pemeriksaan medis umum' },
];
